[package]
name = "farm-staking-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.farm-staking]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.4"
default-features = false
